export const COPY = {
  gymName: 'KONNI MMA GYM',
  city: 'LEIPZIG',
  noEgos: 'NO EGOS.',
  justWork: 'JUST WORK.',
  showUp: 'SHOW UP.',
  mma: 'MMA',
  grappling: 'GRAPPLING',
  striking: 'STRIKING',
  homeOf: 'HOME OF KONNI MMA GYM.',
  locationSoon: 'Standort wird bald bekannt gegeben.',
  fightSoon: 'THE FIGHT',
  startsSoon: 'STARTS SOON.',
  openingSoon: 'OPENING SOON',
  moreSoon: 'Weitere Informationen folgen.',
  waitlistKicker: 'Warteliste',
  waitlistLead: 'Standort, Eröffnung und erste Trainingstermine — direkt in dein Postfach.',
  waitlistEmail: 'E-Mail',
  waitlistName: 'Vorname',
  waitlistSubmit: 'Auf die Liste',
  waitlistPending: 'Einen Moment…',
  waitlistConsent: 'Ich will Infos zur Eröffnung per E-Mail und akzeptiere die',
  waitlistPrivacy: 'Datenschutzerklärung',
  waitlistInvalid: 'Bitte Vorname, gültige E-Mail und Einwilligung eintragen.',
  waitlistError: 'Das hat nicht geklappt. Versuch es gleich noch einmal.',
  waitlistRate: 'Zu viele Versuche. Warte kurz und versuch es erneut.',
  waitlistSuccessEmail: 'Schau in dein Postfach und bestätige die Anmeldung. Danach bist du auf der Liste.',
  waitlistSuccessListed: 'Du stehst auf der Liste. Wir schreiben, sobald Standort und Eröffnung feststehen.',
  waitlistSuccessSaved: 'Du stehst auf der Liste. Sobald der Mailversand verbunden ist, gehen die Infos raus.',
  waitlistSuccessDuplicate: 'Diese Adresse steht schon auf der Liste. Du bekommst die nächsten Infos automatisch.',
  waitlistConfirmed: 'Anmeldung bestätigt. Du bekommst die Infos zur Eröffnung.',
} as const
